vich_uploader:
    db_driver: orm

    mappings:
        portadas:
            uri_prefix: '%uploads_paths%'
            upload_destination: '%kernel.project_dir%/public/%uploads_paths%'
        
        foto_autores:
            uri_prefix: '%fotos_autores%'
            upload_destination: '%kernel.project_dir%/public/%fotos_autores%'
